CREATE TABLE `{product}` (
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `title` varchar(255) NOT NULL default '',
    `slug` varchar(255) NOT NULL default '',
    `summary` text,
    `image` varchar(255) NOT NULL default '',
    `path` varchar(16) NOT NULL default '',
    `order` int(10) unsigned NOT NULL default '0',
    `hits` int(10) unsigned NOT NULL default '0',
    `status` tinyint(1) unsigned NOT NULL default '1',
    `time_create` int(10) unsigned NOT NULL default '0',
    `sales` int(10) unsigned NOT NULL default '0',
    `stock` int(10) unsigned NOT NULL default '0',
    `price` decimal(16,2) NOT NULL default '0.00',
    `price_title` varchar(255) NOT NULL default '',
    `field_1_title` varchar(255) NOT NULL default '',
    `field_2_title` varchar(255) NOT NULL default '',
    `field_3_title` varchar(255) NOT NULL default '',
    `field_4_title` varchar(255) NOT NULL default '',
    `field_5_title` varchar(255) NOT NULL default '',
    `field_6_title` varchar(255) NOT NULL default '',
    `field_7_title` varchar(255) NOT NULL default '',
    `field_8_title` varchar(255) NOT NULL default '',
    `field_9_title` varchar(255) NOT NULL default '',
    `field_10_title` varchar(255) NOT NULL default '',
    PRIMARY KEY (`id`),
    UNIQUE KEY `slug` (`slug`),
    KEY `status` (`status`),
    KEY `order` (`order`),
    KEY `price` (`price`),
    KEY `sales` (`sales`),
    KEY `stock` (`stock`)
);

CREATE TABLE `{detail}` (
    `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
    `product` int(10) unsigned NOT NULL default '0',
    `uid` int(10) unsigned NOT NULL default '0',
    `sales_is` int(10) unsigned NOT NULL default '0',
    `sales_price` decimal(16,2) NOT NULL default '0.00',
    `time_create` int(10) unsigned NOT NULL default '0',
    `time_sales` int(10) unsigned NOT NULL default '0',
    `status` tinyint(1) unsigned NOT NULL default '1',
    `order` int(10) unsigned NOT NULL default '0',
    `field_1` varchar(255) NOT NULL default '',
    `field_2` varchar(255) NOT NULL default '',
    `field_3` varchar(255) NOT NULL default '',
    `field_4` varchar(255) NOT NULL default '',
    `field_5` varchar(255) NOT NULL default '',
    `field_6` varchar(255) NOT NULL default '',
    `field_7` varchar(255) NOT NULL default '',
    `field_8` varchar(255) NOT NULL default '',
    `field_9` varchar(255) NOT NULL default '',
    `field_10` varchar(255) NOT NULL default '',
    PRIMARY KEY (`id`),
    KEY `product` (`product`),
    KEY `sales_is` (`sales_is`),
    KEY `uid` (`uid`),
    KEY `order` (`order`),
    KEY `time_create` (`time_create`),
    KEY `product_sales_is` (`product`, `sales_is`),
    KEY `uid_sales_is` (`uid`, `sales_is`)
);

CREATE TABLE `{order}` (
    `id` int(10) unsigned NOT NULL auto_increment,
    `uid` int(10) unsigned NOT NULL default '0',
    `ip` char(15) NOT NULL default '',
    `status_order` tinyint(1) unsigned NOT NULL default '0',
    `status_payment` tinyint(1) unsigned NOT NULL default '0',
    `time_create` int(10) unsigned NOT NULL default '0',
    `time_payment` int(10) unsigned NOT NULL default '0',
    `product_price` decimal(16,2) NOT NULL default '0.00',
    `paid_price` decimal(16,2) NOT NULL default '0.00',
    `product` int(10) unsigned NOT NULL default '0',
    `detail` int(10) unsigned NOT NULL default '0',
    `payment_method` enum('online','offline') NOT NULL default 'online',
    `payment_adapter` varchar(64) NOT NULL default '',
    PRIMARY KEY (`id`),
    KEY `uid` (`uid`),
    KEY `status_order` (`status_order`),
    KEY `status_payment` (`status_payment`),
    KEY `time_create` (`time_create`),
    KEY `time_payment` (`time_payment`),
    KEY `product` (`product`),
    KEY `detail` (`detail`)
);

CREATE TABLE `{user}` (
    `id` int(10) unsigned NOT NULL auto_increment,
    `uid` int(10) unsigned NOT NULL default '0',
    `first_name` varchar(255) NOT NULL default '',
    `last_name` varchar(255) NOT NULL default '',
    `email` varchar(64) NOT NULL default '',
    `phone` varchar(16) NOT NULL default '',
    `mobile` varchar(16) NOT NULL default '',
    `company` varchar(255) NOT NULL default '',
    `address` text,
    `country` varchar(64) NOT NULL default '',
    `city` varchar(64) NOT NULL default '',
    `zip_code` varchar(16) NOT NULL default '',
    `number` int(10) unsigned NOT NULL default '0',
    PRIMARY KEY (`id`),
    KEY `uid` (`uid`)
);