<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
	<h3><?php echo $this->escape($title); ?></h3>
	<?php if (empty($list)) { ?>
	<div class="alert alert-danger">
		<?php _e('You dont add any details for this products'); ?>
	</div>
	<?php } else { ?>
	<table id="detail-list" class="table table-striped table-bordered table-condensed text-center">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Create time'); ?></th>
			<th><?php _e('Is sales'); ?></th>
			<th><?php _e('Sales time'); ?></th>
			<th><?php _e('Sales price'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($list as $detail) { ?>
		<tr>
			<td><?php echo $this->escape($detail['id']); ?></td>
			<td><?php echo $this->escape($detail['time_create_view']); ?></td>
			<td><?php echo $this->escape($detail['sales_is_view']); ?></td>
			<td><?php echo $this->escape($detail['time_sales_view']); ?></td>
			<td><?php echo $this->escape($detail['sales_price_view']); ?></td>
			<td>
				<a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('controller' => 'detail', 'action' => 'edit', 'id' => $detail['id'], 'product' => $product['id'])); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
			</td>
		</tr>
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
	<?php } ?>
</div>