<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
	<p>
	   <a class="btn btn-primary" title="<?php _e('Add product'); ?>" href="<?php echo $this->url('', array('controller' => 'product', 'action' => 'update')); ?>"><i class="fa fa-folder-open"></i> <?php _e('Add product'); ?></a>
	</p>
	<h3><?php _e('List of product'); ?></h3>
	<table id="product-list" class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Title'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($list as $product) { ?>
		<?php
		if($product['status'] == 1) {
			$labelIdClass = 'label-success';	
		} else {
			$labelIdClass = 'label-warning';	
		}	
		?>
		<tr>
			<td><span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($product['id']); ?></span></td>
			<td>
				<?php echo $this->escape($product['title']); ?>
			</td>
			<td>
				<a class="btn btn-primary" title="<?php _e('View'); ?>" href="<?php echo $product['productUrl']; ?>"><i class="fa fa-eye"></i> <?php _e('View'); ?></a>
				<a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'update', 'id' => $product['id'])); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
				<a class="btn btn-primary" title="<?php _e('View detail'); ?>" href="<?php echo $this->url('', array('controller' => 'detail', 'action' => 'view', 'product' => $product['id'])); ?>"><i class="fa fa-eye"></i> <?php _e('View detail'); ?></a>
				<a class="btn btn-primary" title="<?php _e('Add detail'); ?>" href="<?php echo $this->url('', array('controller' => 'detail', 'action' => 'add', 'product' => $product['id'])); ?>"><i class="fa fa-plus"></i> <?php _e('Add detail'); ?></a>
			</td>
		</tr>
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
	<p>
		<span class="label label-success"><?php _e('Published'); ?></span>
		<span class="label label-warning"><?php _e('Pending review'); ?></span>
		<span class="label label-danger"><?php _e('Trash'); ?></span>
	</p>
</div>